[package]
name = "cantelope"
version = "0.1.0"
edition = "2024"

[features]
default = ["plot", "not_wasm", "socket"]
socket = ["dep:socketcan"]
plot = ["dep:plotters-iced2", "dep:plotters", "dep:iced", "dep:iced_aw", "dep:rfd"]
not_wasm = ["dep:ctrlc"]
wasm = ["dep:iced_web"]
end_data_on_close = []
no_control_row = []
python = ["dep:pyo3"]

[dependencies]
socketcan = { version = '3.5.0', optional = true }
ctrlc = {version = "3.4", optional = true}
#dbc-rs = "0.4"
dbc-rs = { git = "https://github.com/Rombutan/dbc-rs.git" }
candump = { git = "https://github.com/Rombutan/candump-rs.git" }
arrow = { version = "57.2.0", default-features = false }
parquet = { version = "57.2.0", default-features = false, features = ["arrow", "snap"] }
tokio = { version = "1.1", default-features = false, features = ["rt", "rt-multi-thread", "macros", "sync"] }
bytemuck = { version = "1.14", features = ["derive"] }
crossbeam-channel = "0.5"
udp-stream = "0.0.12"
socket2 = "0.6.3"

# stuff for gui
iced = { version = "0.14", features = ["canvas", "tokio"], optional = true}
iced_web = {version="0.4", optional = true}
plotters = {version = "0.3", optional = true}
plotters-iced2 = {version = "0.14", optional = true}
smol_str = "0.3.6"
iced_aw = {version = "0.13.1", optional = true}

rfd = {version = "0.17.2", optional = true}
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
itertools = "0.14.0"
pyo3 = { version = "0.28", features = ["auto-initialize"], optional = true }
ffi = "0.1.1"

[profile.release]
opt-level = 3

[[bin]]
name = "cantelope"
path = "src/main.rs"

[[bin]]
name = "sender"
path = "src/sender.rs"
required-features = ["socket"]

[[bin]]
name = "relay"
path = "src/relay.rs"
