dbcfile = "fs.dbc"
input = "192.168.0.1:1535"
output = ""
candatainput = "TcpRemote"
cache_ms = 0.0
aux_outputs = []
socketout = ""
plots = [["VCU_ETC_IMPLAUSIBILITY_APPS_OUT_OF_RANGE", "VCU_ETC_IMPLAUSIBILITY_BPPS_OUT_OF_RANGE", "VCU_ETC_IMPLAUSIBILITY_APPS_DEVIATION", "VCU_ETC_IMPLAUSIBILITY_BSE_OUT_OF_RANGE", "VCU_ETC_IMPLAUSIBILITY_BRAKE_AND_ACCEL"], ["VCU_ETC_BRAKE_PRESSSURE_FRONT", "VCU_ETC_BRAKE_PRESSSURE_REAR", "VCU_ETC_BRAKE_PEDAL_TRAVEL", "VCU_ETC_ACCEL_PEDAL_TRAVEL", "VCU_ETC_BPPS_HE", "VCU_ETC_APPS2_HE", "VCU_ETC_APPS1_HE"], ["VCU_ETC_READY_TO_DRIVE", "VCU_ETC_RTD_BUTTON_PRESSED"]]
regrens = []
regrens_raw = "SME_THROTL_PowerReady]0,SME_TEMP_FaultCode[1,VCU_ETC_MOTOR_ENABLED]0"
en_ipm = false
en_aux = true
python = ""
